- hosts: localhost
  vars: 
    - admin_base_url: "http://192.168.99.100:8001"
    - api_base_url: "http://192.168.99.100:8000"
  
  tasks:
    - name: Register APIs
      kong_api:
        kong_admin_uri: "{{admin_base_url}}"     
        name: "{{item.name}}"
        upstream_url: "{{item.upstream_url}}"
        request_host: "{{item.request_host}}"       
        state: present
      with_items:
        - name: "mockbin"
          upstream_url: "http://mockbin.com"
          request_host: "mockbin.com"
        - name: "Github"
          upstream_url: "https://github.com"
          request_host: "github.com"

    - name: Update APIs
      kong_api:
        kong_admin_uri: "{{admin_base_url}}"     
        name: "{{item.name}}"
        upstream_url: "{{item.upstream_url}}"
        request_host: "{{item.request_host}}"       
        state: latest
      with_items:
        - name: "Github"
          upstream_url: "https://api.github.com"
          request_host: "github.com"
      register: result

    - debug: var=result

#    - name: Delete mockbin 
#      kong_api:
#        kong_admin_uri: "{{admin_base_url}}"     
#        name: "Mockbin"  
#        state: absent   

    - name: Output API 
      kong_api:
        kong_admin_uri: "{{admin_base_url}}"
        state: list    
      register: result

    - name: Add request transformer to mockbin 
      kong_plugin:
        kong_admin_uri: "{{admin_base_url}}"
        api_name: "mockbin"
        plugin_name: "request-transformer"
        config: 
          "config.add.headers": "x-new-header:some_value, x-another-header:some_value"
          "config.add.querystring": "new-param:some_value, another-param:some_value"
          "config.add.form": "new-form-param:some_value, another-form-param:some_value"
          "config.remove.headers": "x-toremove, x-another-one"
          "config.remove.querystring": "param-toremove, param-another-one"
          "config.remove.form": "formparam-toremove, formparam-another-one"
        state: present  
      register: result  

    - name: Show plugins
      kong_plugin:
        kong_admin_uri: "{{admin_base_url}}"
        api_name: "mockbin"
        state: list
      register: plugins 

    - debug: var=plugins

    - name: Delete request transformer from mockbin
      kong_plugin:
        kong_admin_uri: "{{admin_base_url}}"        
        api_name: "mockbin"        
        plugin_id: "{{plugins.meta.data.0.id}}"
        state: absent

    - debug: var=result   

    - name: Add some consumers
      kong_consumer:
        kong_admin_uri: "{{admin_base_url}}"
        username: "{{item}}"
        state: present
      with_items:
        - bill
        - bob
        - barry

    - name: Remove bill
      kong_consumer:
        kong_admin_uri: "{{admin_base_url}}"
        username: bill
        state: absent
