---

kong_services:
  - name: httpbin
    host: httpbin.org
    routes:
      - hosts:
          - localhost
          - example.com
        paths:
          - /
        state: present
    state: present

  - name: ifconfig
    host: ifconfig.co
    state: absent

kong_consumers:
  - username: ansible
    credentials:
      - type: key-auth
        config:
          key: 123456
      - type: basic-auth
        config:
          username: ansible
          password: qwerty
    state: present

kong_plugins:
  - name: basic-auth
    service: httpbin
    config:
      hide_credentials: true
    state: present

kong_certificates:
  - sni: example.com
    cert: "{{ lookup('file', 'example_com.cert.pem') }}"
    key: "{{ lookup('file', 'example_com.key.pem') }}"
    state: present
